In [2]:
import numpy as np
import pandas as pd

In [5]:
data=pd.read_csv('play_tennis.csv')
data.drop(columns=['day'],inplace=True)
data.head()

    outlook  temp humidity    wind play
0     Sunny   Hot     High    Weak   No
1     Sunny   Hot     High  Strong   No
2  Overcast   Hot     High    Weak  Yes
3      Rain  Mild     High    Weak  Yes
4      Rain  Cool   Normal    Weak  Yes

In [6]:
# Problem 1
# Outlook = Sunny, Temp = Hot, Humidity = High, Wind = Weak
# Play or No Play?

In [7]:
# Solution
# P(Yes | Sunny, Hot, High, Weak) = P(Sunny | Yes) * P(Hot | Yes) * P(High | Yes) * P(Weak | Yes) * P(Yes)
# P(No | Sunny, Hot, High, Weak) = P(Sunny | No) * P(Hot | No) * P(High | No) * P(Weak | No) * P(No)
# Compare and decide using the Maximum a posteriori rule

In [8]:
# Problem 2
# Outlook = Overcast, Temp = Cold, Humidity = Low, Wind = Weak
# Play or No Play?

In [10]:
# Solution
# P(Yes | Overcast, Cold, Low, Weak) = P(Overcast | Yes) * P(Cold | Yes) * P(Low | Yes) * P(Weak | Yes) * P(Yes)
# P(No | Overcast, Cold, Low, Weak) = P(Overcast | No) * P(Cold | No) * P(Low | No) * P(Weak | No) * P(No)
# Compare and decide using the Maximum a posteriori rule

In [12]:
# Training 

# LookUp table (Dictionary)

# Testing

In [15]:
data['play'].value_counts()    # type of output values

play
Yes    9
No     5
Name: count, dtype: int64

In [20]:
py=9/14   # P(Yes)
pn=5/14   # P(No)

In [16]:
# Outlook
pd.crosstab(data['outlook'],data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [17]:
pon=0
prn=2/5
psn=3/5

poy=4/9
pry=3/9
psy=2/9

In [18]:
# temp
pd.crosstab(data['temp'],data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [19]:
pcoolno=1/5
photno=2/5
pmildno=2/5

pcoolyes=3/9
photyes=2/9
pmildyes=4/9

In [21]:
# Humidity
pd.crosstab(data['humidity'],data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [22]:
phighyes=3/9
pnormalyes=6/9
phighno=4/5
pnormalno=1/5

In [23]:
# wind 
pd.crosstab(data['wind'],data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [24]:
pstry=3/9
pwky=6/9
pstrn=3/5
pwkn=2/5

## Problem 1
## Outlook = Sunny, Temp = Hot, Humidity = High, Wind = Weak
## Play or No Play?

In [29]:
Pyes=py*psy*photyes*phighyes*pwky
print("P(Yes | Outlook = Sunny, Temp = Hot, Humidity = High, Wind = Weak) = ",Pyes)

P(Yes | Outlook = Sunny, Temp = Hot, Humidity = High, Wind = Weak) =  0.007054673721340388

In [30]:
Pno=pn*psn*photno*phighno*pwkn
print("P(No | Outlook = Sunny, Temp = Hot, Humidity = High, Wind = Weak) = ",Pno)

P(No | Outlook = Sunny, Temp = Hot, Humidity = High, Wind = Weak) =  0.02742857142857143

## since Pyes>Pno
## No Play given Outlook = Sunny, Temp = Hot, Humidity = High, Wind = Weak