In [21]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
for dirname, _, filenames in os.walk('heart_disease.csv'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [22]:
df=pd.read_csv('heart_disease.csv')

In [31]:
df = df.drop('num', axis=1)

In [32]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target_binary
0,63.0,1,1,145.0,233.0,1,2,150.0,0,2.3,3,0.0,6.0,0
1,67.0,1,4,160.0,286.0,0,2,108.0,1,1.5,2,3.0,3.0,1
2,67.0,1,4,120.0,229.0,0,2,129.0,1,2.6,2,2.0,7.0,1
3,37.0,1,3,130.0,250.0,0,0,187.0,0,3.5,3,0.0,3.0,0
4,41.0,0,2,130.0,204.0,0,2,172.0,0,1.4,1,0.0,3.0,0

In [33]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=2)

In [34]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [35]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [36]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [37]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [38]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.8780487804878049
Accuracy of Decision Trees 0.8097560975609757

In [40]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))

Logistic Regression Confusion Matrix

    0   1
0  99  11
1  14  81

In [41]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))

Decision Tree Confusion Matrix

    0   1
0  92  18
1  21  74

In [42]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2

In [43]:
result.sample(10)

     Actual Label  Logistic Regression Prediction  Decision Tree Prediction
752             1                               1                         1
355             0                               0                         0
695             1                               1                         1
232             1                               1                         1
426             0                               0                         1
199             1                               0                         0
239             0                               0                         0
164             0                               0                         1
230             0                               0                         0
775             1                               1                         1

In [44]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [45]:
print("For Logistic regression Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))

For Logistic regression Model
--------------------------------------------------
    0   1
0  99  11
1  14  81
--------------------------------------------------
Precision -  0.8804347826086957
Recall -  0.8526315789473684
F1 score -  0.8663101604278075

In [46]:
print("For DT Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred2))
print("Recall - ",recall_score(y_test,y_pred2))
print("F1 score - ",f1_score(y_test,y_pred2))

For DT Model
--------------------------------------------------
    0   1
0  92  18
1  21  74
--------------------------------------------------
Precision -  0.8043478260869565
Recall -  0.7789473684210526
F1 score -  0.7914438502673797

# Here we're getting these scores for all classes, be it positive or negative.

In [52]:
f1_score(y_test,y_pred2,average=None)

array([0.82511211, 0.79144385])

In [53]:
precision_score(y_test,y_pred2,average=None)

array([0.81415929, 0.80434783])

In [54]:
recall_score(y_test,y_pred2,average=None)

array([0.83636364, 0.77894737])

# Macro and weighed metrics

In [51]:
precision_score(y_test,y_pred2,average='macro')

0.8092535590611774

In [55]:
precision_score(y_test,y_pred2,average='weighted')

0.8096125151324619

In [56]:
from sklearn.metrics import classification_report

In [57]:
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.88      0.90      0.89       110
           1       0.88      0.85      0.87        95

    accuracy                           0.88       205
   macro avg       0.88      0.88      0.88       205
weighted avg       0.88      0.88      0.88       205